# this workflow will be triggered when
#
#  1. a pull request is raised
#  2. a push to 'develop' branch takes place
#  3. a release tag is created on the repo
#
# build and test will be performed when the action is triggered. for 2 and 3, a container image will be created
# and pushed to Github Container Resitry. The following tagging logic will be applied:
#
#  for push to develop branch, develop-YYYYMMDD-HHMISS-SHA7. the tagging should be sortable by chronological order so that
#  it can be picked up by CD tools, e.g. FluxCD, for updating the deployment automatically
#
#  for push to main xxx (not yet implemented)
#  for new tag, the image tag will be same as the repository tag, with -SHA7 as suffix. e.g. v0.1.0-ab23dfe

on:
  push:
    branches:
    - develop
    - feature/*
    tags:
    - v[0-9].*

  pull_request:
    types: [opened, edited, reopened]

  workflow_dispatch:

jobs:
  python-test-and-build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Linting
      if: success()
      run: |
        flake8 --count --show-source --statistics

    - name: Unit tests
      run: |
        pytest -v -s
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: set image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,suffix=-{{sha}},event=tag
          type=raw,value=develop-{{date 'YYYYMMDD-HHmmss' tz='Asia/Singapore'}}-{{sha}},enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
        flavor: |
          latest=false
        labels: |
          org.opencontainers.image.source https://github.com/{{ ${{ github.repository }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to github registry
      if: steps.meta.outputs.tags != ''
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      if: steps.meta.outputs.tags != ''
      uses: docker/build-push-action@v3
      with:
        platforms: "linux/amd64,linux/arm64"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Delete old images
      if: steps.meta.outputs.tags != ''
      uses: actions/delete-package-versions@v4
      with:
        owner: ${{ github.repository_owner }}
        package-name: ${{ github.event.repository.name }}
        package-type: container
        min-versions-to-keep: 10
        ignore-versions: latest
        token: ${{ secrets.GITHUB_TOKEN }}
